In [56]:
import numpy as np
import matplotlib.pyplot as plt
import quandl 
import requests 
import json 
import pandas as pd 
import datetime

# 2 Time Series Gradient Descent Exercise in Python

## OLS estimates  from standard OLS formula

Bitcoin Daily Time series from 2016-01-01 to 2021-01-01 using QUANDL API

In [3]:
quandl.ApiConfig.api_key = 'a9NejCNZWKHWyyWRQ2wP'

In [94]:
#Home_Depot = quandl.get('EOD/HD') 
x =quandl.get('BITFINEX/BTCUSD', start_date='2016-01-01', end_date='2021-01-01')
#Home_Depot = quandl.get('BTC/US') 
x.head()
#type(x)

              High     Low      Mid    Last     Bid     Ask        Volume
Date
2016-01-01  436.49  426.26  433.910  433.78  433.83  433.99  12922.080199
2016-01-02  435.80  430.00  433.330  433.20  433.20  433.46   6658.092194
2016-01-03  433.79  421.73  427.905  427.98  427.76  428.05  18644.760056
2016-01-04  435.67  426.20  434.475  434.49  434.47  434.48  13092.850666
2016-01-05  434.91  427.91  432.090  431.82  431.96  432.22  11532.984890

In [95]:
x=x['High']
x

Date
2016-01-01      436.49
2016-01-02      435.80
2016-01-03      433.79
2016-01-04      435.67
2016-01-05      434.91
                ...
2020-12-28    27442.00
2020-12-29    27228.00
2020-12-30    28977.00
2020-12-31    29286.00
2021-01-01    29620.00
Name: High, Length: 1792, dtype: float64

In [98]:
x=np.array(x)
type(x)

numpy.ndarray

In [99]:
#Home_Depot.plot(y='Adj_Close', figsize=(10,10))
#plt.xlabel('Date', fontsize=18) 
#plt.ylabel( 'Adj_Close' , fontsize=18) 
#plt.title("Home Depot End of Day price") 
#plt.show()

## Eherium Daily Time series from 2016-01-01 to 2021-01-01 using CRYPTOCOMPARE API

In [112]:
lim = '100'
pair = ['ETH'] 
coins = pd.DataFrame() 
my_crypto_key = "C370e1baf8f2aedafb5e730b7c103cf0ff064111eca3b0860878dcf47ec2457e"

In [120]:

URL_A = 'https://min-api.cryptocompare.com/data/histoday?fsym=ETH&tsym=USD&1imit=1000&api_key=' 
URL = URL_A + my_crypto_key 
URL
https://min-api.cryptocompare.com/data/v2/histoday?fsym=ETH&tsym=USD&limit=100&api_key=C370e1baf8f2aedafb5e730b7c103cf0ff064111eca3b0860878dcf47ec2457e

'https://min-api.cryptocompare.com/data/histoday?fsym=ETH&tsym=USD&1imit=1000&api_key=C370e1baf8f2aedafb5e730b7c103cf0ff064111eca3b0860878dcf47ec2457e'

In [119]:
data = requests.get(URL) 
json_data = data.json() 
table = pd.json_normalize(json_data, 'Data').set_index('time')
table.head()

,high,low,open,volumefrom,volumeto,close,conversionType,conversionSymbol
time,,,,,,,,
1624406400,2044.91,1827.20,1880.83,714905.63,1.416402e+09,1968.56,direct,
1624492800,2034.57,1886.17,1968.56,448512.52,8.825040e+08,1989.01,direct,
1624579200,2019.45,1791.99,1989.01,882983.22,1.653238e+09,1810.27,direct,
1624665600,1851.36,1717.91,1810.27,575329.88,1.021388e+09,1830.94,direct,
1624752000,1984.58,1808.20,1830.94,583203.44,1.092710e+09,1983.33,direct,

In [127]:
table.index = pd.to_datetime(table.index , unit='s')
table

,high,low,open,volumefrom,volumeto,close,conversionType,conversionSymbol
time,,,,,,,,
2021-06-23,2044.91,1827.20,1880.83,714905.63,1.416402e+09,1968.56,direct,
2021-06-24,2034.57,1886.17,1968.56,448512.52,8.825040e+08,1989.01,direct,
2021-06-25,2019.45,1791.99,1989.01,882983.22,1.653238e+09,1810.27,direct,
2021-06-26,1851.36,1717.91,1810.27,575329.88,1.021388e+09,1830.94,direct,
2021-06-27,1984.58,1808.20,1830.94,583203.44,1.092710e+09,1983.33,direct,
2021-06-28,2143.60,1961.83,1983.33,638008.18,1.308344e+09,2083.80,direct,
2021-06-29,2245.38,2075.64,2083.80,455104.86,9.904993e+08,2165.61,direct,
2021-06-30,2287.05,2089.55,2165.61,518346.72,1.128165e+09,2276.14,direct,
2021-07-01,2277.05,2074.67,2276.14,499798.16,1.069055e+09,2109.29,direct,
2021-07-02,2159.25,2018.32,2109.29,411011.61,8.555462e+08,2155.65,direct,
2021-07-03,2238.77,2113.24,2155.65,233568.59,5.117569e+08,2227.18,direct,
2021-07-04,2387.73,2190.78,2227.18,297638.95,6.903330e+08,2323.27,direct,
2021-07-05,2323.53,2159.57,2323.27,364621.13,8.170322e+08,2196.71,direct,
2021-07-06,2349.66,2194.97,2196.71,371318.48,8.526733e+08,2322.63,direct,
2021-07-07,2408.53,2294.71,2322.63,327127.26,7.711741e+08,2317.12,direct,
2021-07-08,2324.72,2084.63,2317.12,766987.58,1.669544e+09,2114.51,direct,
2021-07-09,2186.26,2048.12,2114.51,594562.44,1.261710e+09,2145.67,direct,
2021-07-10,2190.77,2075.55,2145.67,254162.69,5.392041e+08,2110.47,direct,
2021-07-11,2173.19,2081.93,2110.47,158610.10,3.372967e+08,2140.45,direct,
2021-07-12,2168.12,2007.79,2140.45,343756.40,7.131063e+08,2032.88,direct,
2021-07-13,2046.08,1917.90,2032.88,407842.50,8.084087e+08,1940.61,direct,
2021-07-14,2019.42,1866.25,1940.61,389974.78,7.582285e+08,1994.22,direct,
2021-07-15,2039.24,1881.40,1994.22,443146.82,8.585156e+08,1918.17,direct,
2021-07-16,1964.79,1850.35,1918.17,358403.19,6.821332e+08,1877.05,direct,
2021-07-17,1918.93,1849.84,1877.05,279072.61,5.262624e+08,1899.96,direct,
2021-07-18,1993.26,1881.84,1899.96,291029.97,5.634445e+08,1891.96,direct,
2021-07-19,1918.43,1806.49,1891.96,409977.30,7.550830e+08,1818.60,direct,
2021-07-20,1840.59,1720.11,1818.60,640378.57,1.129314e+09,1786.52,direct,
2021-07-21,2030.25,1755.61,1786.52,582170.14,1.115296e+09,1994.98,direct,
2021-07-22,2046.29,1949.15,1994.98,382331.84,7.646264e+08,2024.74,direct,
2021-07-23,2076.18,2015.69,2024.74,40856.33,8.380818e+07,2058.76,direct,

In [105]:
coins = pd.concat([coins, table.high],  axis=1) 
coins.columns = pair 
coins

ValueError: Length mismatch: Expected axis has 2 elements, new values have 3 elements